### Add a New Post
POST http://localhost:3000/post
Content-Type: application/json

{
    "sender": "user123",
    "content": "Hello, this is my first post!"
}

### Get All Posts
GET http://localhost:3000/post

### Get a Post by ID
GET http://localhost:3000/post/67460ea71ab399fbc8d97141

### Get Posts by Sender
GET http://localhost:3000/post?sender=user123

### Update a Post
PUT http://localhost:3000/post/67460ea71ab399fbc8d97141
Content-Type: application/json

{
    "content": "This is the updated3 post content."
}




### Add a New Comment
POST http://localhost:3000/comment
Content-Type: application/json

{
    "sender": "user123",
    "content": "Hello, this is my first comment!",
    "postId": "67460ea71ab399fbc8d97141"
}

### Get All Comments by PostId
GET http://localhost:3000/comment/post/67460ea71ab399fbc8d97141

### Get a Comment by ID
GET http://localhost:3000/comment/6746378de8910ecde987b0bc

### Delete a Comment By ID
DELETE http://localhost:3000/comment/6746378de8910ecde987b0bc

### Update a Comment
PUT http://localhost:3000/comment/6746378de8910ecde987b0bc
Content-Type: application/json

{
    "content": "This is the updated3 comment content."
}

