### Add a New Post
POST http://localhost:3000/post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjA4NDA0ODQzNDcyNDQzMTAyIiwiaWF0IjoxNzM1NTY5MTM5LCJleHAiOjE3MzU1Nzk5Mzl9.vAiopJ-DpFTUtbr8ZHe4eS2lemIfkfSXtFtqfuG6p-U
Content-Type: application/json

{
  "content": "Hello, this is my second post!"
}

### Get All Posts
GET http://localhost:3000/post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjE4NTExMDQzMjU4OTUyMTY1IiwiaWF0IjoxNzM1NDEzNDQ5LCJleHAiOjE3MzU0OTk4NDl9.R0B8P1aZk0NzoWfqcmyxW2qUKyo4118UNU5wtBdyhxs

### Get a Post by ID
GET http://localhost:3000/post/6772af0ac4525a92d90d8370
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjMzNTkxNjYyNDQ3ODUyMTY2IiwiaWF0IjoxNzM1NTY3MDQ4LCJleHAiOjE3MzU1Nzc4NDh9.axibakPpUhfQDcYCE1Ltc3dN3tAZ-o-WtH_DfPg2qyY

### Get Posts by UserId
GET http://localhost:3000/post?userId=677041219ebf9d7fa381d4e0
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjMzNTkxNjYyNDQ3ODUyMTY2IiwiaWF0IjoxNzM1NTY3MDQ4LCJleHAiOjE3MzU1Nzc4NDh9.axibakPpUhfQDcYCE1Ltc3dN3tAZ-o-WtH_DfPg2qyY

### Update a Post
PUT http://localhost:3000/post/6772b2b15ff8f25127205534
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcyYjA2MWM0NTI1YTkyZDkwZDgzOGEiLCJyYW5kb20iOiIwLjM5MzcwNjE3OTg3Njk3NzQiLCJpYXQiOjE3MzU1Njk2MTQsImV4cCI6MTczNTU4MDQxNH0.Ya9yxyehMd6d1-8iNxpp0-oAYonYavfXPYqNqQC2I2k
Content-Type: application/json

{
    "content": "This is the updated post content 4."
}



### Add a New Comment
POST http://localhost:3000/comment
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjMzNTkxNjYyNDQ3ODUyMTY2IiwiaWF0IjoxNzM1NTY3MDQ4LCJleHAiOjE3MzU1Nzc4NDh9.axibakPpUhfQDcYCE1Ltc3dN3tAZ-o-WtH_DfPg2qyY
Content-Type: application/json

{
    "content": "Hello, this is my first comment3!",
    "postId": "6772af0ac4525a92d90d8370"
}

### Get All Comments by PostId
GET http://localhost:3000/comment/post/6770243fb28705c49808aa5f
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjMzNTkxNjYyNDQ3ODUyMTY2IiwiaWF0IjoxNzM1NTY3MDQ4LCJleHAiOjE3MzU1Nzc4NDh9.axibakPpUhfQDcYCE1Ltc3dN3tAZ-o-WtH_DfPg2qyY

### Get a Comment by ID
GET http://localhost:3000/comment/67702489b28705c49808aa73
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjMzNTkxNjYyNDQ3ODUyMTY2IiwiaWF0IjoxNzM1NTY3MDQ4LCJleHAiOjE3MzU1Nzc4NDh9.axibakPpUhfQDcYCE1Ltc3dN3tAZ-o-WtH_DfPg2qyY

### Delete a Comment By ID
DELETE http://localhost:3000/comment/67702489b28705c49808aa73
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjE4NTExMDQzMjU4OTUyMTY1IiwiaWF0IjoxNzM1NDEzNDQ5LCJleHAiOjE3MzU0OTk4NDl9.R0B8P1aZk0NzoWfqcmyxW2qUKyo4118UNU5wtBdyhxs

### Update a Comment
PUT http://localhost:3000/comment/67702489b28705c49808aa73
Content-Type: application/json
Authorization: JWT Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NzcwNDEyMTllYmY5ZDdmYTM4MWQ0ZTAiLCJyYW5kb20iOiIwLjMzNTkxNjYyNDQ3ODUyMTY2IiwiaWF0IjoxNzM1NTY3MDQ4LCJleHAiOjE3MzU1Nzc4NDh9.axibakPpUhfQDcYCE1Ltc3dN3tAZ-o-WtH_DfPg2qyY


{
    "content": "This is the updated comment content."
}



### register new user
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "boaz@gmail.com",
    "username": "boazboaz",
    "password": "987654"
}

### login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "boaz@gmail.com",
    "password": "987654"
}
